package in.com.halding_Exception;

public class Exception2 {
	public static void main(String[] args) {
		try {
			
			String  name="rays";
			System.out.println(name.charAt(2));
			
			
		} catch (Exception e) {
			System.out.println(e);
		}		
		
	}

}
